let Products = [
  {
    nameSP: "LEVENTS® | DORAEMON FAMOUS CAT TEE",
    img: "./img/products/p1-1.png",
    price: 370000,
    nametag: "aothun#",
    idproduct: "abc",
    colorr1: "gray",
    colorr2: "red",
    colorr3: "unset",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    img1: "./img/products/p1-1.png",
    img2: "./img/products/p1-2.jpg",
    img3: "./img/products/p1-2.jpg",
  },
  {
    nameSP: "LEVENTS® | DORAEMON COLLAB TEE",
    img: "./img/products/p2-1.png",
    price: 450000,
    nametag: "aothun#",
    idproduct: "",
    colorr1: "brown",
    colorr2: "black",
    colorr3: "unset",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    img1: "./img/products/p2-1.png",
    img2: "./img/products/p2-2.png",
    img3: "./img/products/p2-2.png",
  },
  {
    nameSP: "LEVENTS® DINOSAUR TEE",
    img: "./img/products/p3-1.jpg",
    price: 420000,
    nametag: "aothun#",
    idproduct: "",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr1: " rgb(235, 232, 226)",
    colorr2: "black",
    colorr3: "blue",
    img1: "./img/products/p3-1.jpg",
    img2: "./img/products/p3-2.jpg",
    img3: "./img/products/p3-3.jpg",
  },
  {
    nameSP: "LEVENTS® INSIDE OUT TEE",
    img: "./img/products/p4-1.jpg",
    price: 390000,
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    nametag: "aothun#",
    idproduct: "",
    colorr1: " rgb(235, 232, 226)",
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p4-1.jpg",
    img2: "./img/products/p4-2.jpg",
    img3: "./img/products/p4-2.jpg",
  },
  {
    nameSP: "LEVENTS® LOVEYOU300K SPECIAL TEE",
    img: "./img/products/p5-1.jpg",
    price: 300000,
    nametag: "aothun#",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr1: " rgb(235, 232, 226)",
    colorr2: "unset",
    idproduct: "",
    colorr3: "unset",
    img1: "./img/products/p5-1.jpg",
    img2: "./img/products/p5-1.jpg",
    img3: "./img/products/p5-1.jpg",
  },
  {
    nameSP: "LEVENTS® FUNNY CROCODILE TEE",
    img: "./img/products/p6-1.jpg",
    price: 390000,
    nametag: "aothun#",
    colorr1: "blue",
    idproduct: "",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p6-1.jpg",
    img2: "./img/products/p6.jpg",
    img3: "./img/products/p6-2.jpg",
  },
  {
    nameSP: "LEVENTS® PUNCH VARSITY",
    img: "./img/products/p7-1.jpg",
    price: 890000,
    nametag: "aokhoac#",
    idproduct: "",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr1: "brown",
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p7-1.jpg",
    img2: "./img/products/p7-2.jpg",
    img3: "./img/products/p7-2.jpg",
  },
  {
    nameSP: "LEVENTS® SELFLOVE BOXY TEE",
    img: "./img/products/p8-1.jpg",
    price: 380000,
    idproduct: "",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    nametag: "aothun#",
    colorr1: " rgb(235, 232, 226)",
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p8-1.jpg",
    img2: "./img/products/p8-2.jpg",
    img3: "./img/products/p8-1.jpg",
  },
  {
    nameSP: "LEVENTS® | DORAEMON MINI CAT Polo",
    img: "./img/products/p9-1.jpg",
    price: 405000,
    nametag: "polo#",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    idproduct: "",
    colorr1: " rgb(235, 232, 226)",
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p9-1.jpg",
    img2: "./img/products/p9-2.jpg",
    img3: "./img/products/p9-2.jpg",
  },
  {
    nameSP: "LEVENTS® MINI POPULAR Polo",
    img: "./img/products/p10-1.jpg",
    price: 370000,
    nametag: "polo#",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    idproduct: "",
    colorr1: " rgb(235, 232, 226)",
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p10-1.jpg",
    img2: "./img/products/p10-2.jpg",
    img3: "./img/products/p10-2.jpg",
  },
  {
    nameSP: "LEVENTS® STRIPE Polo",
    img: "./img/products/p11-1.jpg",
    price: 420000,
    idproduct: "",
    nametag: "polo#",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr1: " rgb(235, 232, 226)",
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p11-1.jpg",
    img2: "./img/products/p11-2.jpg",
    img3: "./img/products/p11-2.jpg",
  },
  {
    nameSP: "LEVENTS® CINEMA SHIRT",
    img: "./img/products/p12-1.jpg",
    price: 420000,
    nametag: "somi#",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    idproduct: "",
    colorr1: "brown",
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p12-1.jpg",
    img2: "./img/products/p12-2.jpg",
    img3: "./img/products/p12-2.jpg",
  },
  {
    nameSP: "LEVENTS® CITIES SHIRT",
    img: "./img/products/p13-1.jpg",
    price: 420000,
    nametag: "somi#",
    idproduct: "",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr1: " rgb(235, 232, 226)",
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p13-1.jpg",
    img2: "./img/products/p13-2.jpg",
    img3: "./img/products/p13-2.jpg",
  },
  {
    nameSP: "LEVENTS® | DORAEMON COLLAB ZIPPER Hoodie",
    img: "./img/products/p14-1.jpg",
    price: 645000,
    nametag: "hoodie#",
    idproduct: "",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr1: " rgb(235, 232, 226)",
    colorr2: "gray",
    colorr3: "unset",
    img1: "./img/products/p14-1.jpg",
    img2: "./img/products/p14-2.jpg",
    img3: "./img/products/p14-2.jpg",
  },
  {
    nameSP: "LEVENTS® POPULAR LOGO 2.0 Hoodie",
    img: "./img/products/p15-1.jpg",
    price: 590000,
    nametag: "hoodie#",
    colorr1: "yellow",
    colorr2: "gray",
    idproduct: "",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr3: "black",
    img1: "./img/products/p15-1.jpg",
    img2: "./img/products/p15-2.jpg",
    img3: "./img/products/p15-3.jpg",
  },
  {
    nameSP: "LEVENTS® MINI LOGO ZIPPER Hoodie",
    img: "./img/products/p16-1.jpg",
    price: 620000,
    nametag: "hoodie#",
    colorr1: " rgb(235, 232, 226)",
    colorr2: "gray",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr3: "unset",
    idproduct: "",
    img1: "./img/products/p16-1.jpg",
    img2: "./img/products/p16-2.jpg",
    img3: "./img/products/p16-2.jpg",
  },
  {
    nameSP: "LEVENTS® | DORAEMON COLLAB Hoodie",
    img: "./img/products/p17-1.jpg",
    price: 620000,
    nametag: "hoodie#",
    colorr1: " rgb(235, 232, 226)",
    colorr2: "black",
    colorr3: "unset",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    idproduct: "",
    img1: "./img/products/p17-1.jpg",
    img2: "./img/products/p17-2.jpg",
    img3: "./img/products/p17-2.jpg",
  },
  {
    nameSP: "LEVENTS® BASIC Sweater",
    img: "./img/products/p18-1.jpg",
    price: 490000,
    nametag: "sweater#",
    idproduct: "",
    colorr1: "gray",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    colorr2: "red",
    colorr3: "unset",
    img1: "./img/products/p18-1.jpg",
    img2: "./img/products/p18-2.jpg",
    img3: "./img/products/p18-2.jpg",
  },
  {
    nameSP: "LEVENTS® FUNNY CROCODILE Sweater",
    img: "./img/products/p19-1.jpg",
    price: 490000,
    nametag: "sweater#",
    colorr1: "brown",
    quantity: {
      A: 5,
      B: 4,
      C: 6,
      D: 2,
    },
    idproduct: "",
    colorr2: "black",
    colorr3: "unset",
    img1: "./img/products/p19-1.jpg",
    img2: "./img/products/p19-2.jpg",
    img3: "./img/products/p19-2.jpg",
  },
];

for (let i = 0; i < Products.length; i++) {
  Products[i].idproduct = Products[i].nametag + i;
}
if (JSON.parse(localStorage.getItem("arrayproducts")) == null) {
  localStorage.setItem("arrayproducts", JSON.stringify(Products));
}
function timkiemtheoID(ID) {
  for (let i = 0; i < Products.length; i++) {
    if (Products[i].idproduct == ID) {
      return Products[i];
    }
  }
  return null;
}
